project:
  type: website
  resources:
    - "assets/*"

website:
  title: "Constantin Kühne"
  navbar:
    left:
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



